//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ObsSistem.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;

public partial class belgeTalepModel
{
    public int belgeTalepId { get; set; }
    public string belgeTalepOgrenciNo { get; set; }
    public string belgeTalepTur { get; set; }
};
public partial class isDeneyimleri
{
    public int deneyimId { get; set; }
    public string SirketAdi { get; set; }
    public string Pozisyon { get; set; }
    public DateTime baslangicTarihi { get; set; }
    public DateTime bitisTarihi { get; set; }
    public string isTanimi { get; set; }
    public int ogrenciNumara { get; set; }
}

public partial class talepModel
{
    public string talepId { get; set; }
    public string konu { get; set; }
    public string mesaj { get; set; }
    public string gonderenId { get; set; }
    public string gonderenAd { get; set; }
    public string gonderenSoyad { get; set; }
    public string mesajYanit { get; set; }
    public int durum { get; set; }
}
public class KimlikKartTalepEtModel
{
    public string talepId { get; set; }
    public string OgrenciNo { get; set; }
    // Diğer gerekli özellikleri ekleyebilirsiniz.
}

public partial class sınavModel
{
    public string DERS_ID { get; set; }
    public string DERS_AD { get; set; }
    public string SINAV_TUR { get; set; }
    public string OGRENCI_NOT { get; set; }
    public string SINAV_TARIH { get; set; }
    public string OGRENCI_ID { get; set; }
    public string OGRENCI_SOYAD { get; set; }
    public string OGRENCI_AD { get; set; }
}
public partial class notKartModel
{
    public string DERS_ID { get; set; }
    public string DERS_AD { get; set; }
    public string HARF_NOT { get; set; }
}