//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObsSistem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Security.Permissions;

    public partial class ogrenciModel
    {
        public int NUMARA { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string TC { get; set; }
        public string CINSIYET { get; set; }
        public string DOGUM_TARIHI { get; set; }
        public string E_POSTA { get; set; }
        public string TELEFON_NO { get; set; }
        public string SIFRE { get; set; }
        public string ADRES { get; set; }
        public string BASLANGIC_YILI { get; set; }
        public string BOLUM { get; set; }
        public string DANISMAN { get; set; }

    }
}
