//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObsSistem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NOT
    {
        public int NOT_ID { get; set; }
        public Nullable<int> OGRENCI_ID { get; set; }
        public Nullable<int> DERS_ID { get; set; }
        public Nullable<int> NOTU { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    
      
        //public virtual TBL_DERS TBL_DERS { get; set; }
    }
}
