//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObsSistem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DERS_ALMA
    {
        public int SINAV_ID { get; set; }
        public Nullable<int> DERS_ID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.TimeSpan> SAAT { get; set; }
        public string SINAV_TURU { get; set; }
    
      //  public virtual TBL_DERS TBL_DERS { get; set; }
    }
    public partial class dersAlmaModel
    {
        public int DERS_ALMA_ID;
        public int DERS_ID;
        public int ogrenciNumara;
        public string ogrenciAd;
        public string ogrenciSoyad;
        public string dersAd;
        public int durum;
        public string dersVeren;
        public string dersKod;
        public int kredi;
        public string danisman;
    }
}
