//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObsSistem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    public partial class AkademisyenModel
    {
        public string AkademisyenTC { get; set; }
        public string AkademisyenSifre { get; set; }
        public string AkademisyenAdSoyad { get; set; }
        public string AkademisyenID { get; set; }
        public int AkademisyenDanismanlikDurumu { get; set; }
    
    }
}
