//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObsSistem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    // Models/IsDeneyimModel.cs
    //public class IsDeneyimModel
    //{
    //    public List<Deneyim> Deneyimler { get; set; }

    //    public IsDeneyimModel()
    //    {
    //        Deneyimler = new List<Deneyim>();
    //    }
    //}

    public partial class Deneyim
    {
        public string SirketAdi { get; set; }
        public string Pozisyon { get; set; }
        public string BaslangicTarihi { get; set; }
        public string BitisTarihi { get; set; }
        public string IsTanimi { get; set; }
    }
}
