//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObsSistem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.Web.Razor.Text;

    public partial class dersModel
    {
            public int DERS_ID { get; set; }
            public string DERS_ADI { get; set; }
            public string DERS_KODU { get; set; }
            public int KREDI { get; set; }
            public string BOLUM { get; set; }
            public string DERSI_VEREN { get; set; }
            public string HARF_NOTU { get; set; }
            public int DERS_YARI_YIL { get; set; }
    }
    public partial class dersModel1
    {
        public int DERS_ID { get; set; }
        public string DERS_ADI { get; set; }
        public string DERS_KODU { get; set; }
        public int KREDI { get; set; }
        public string BOLUM { get; set; }
        public string DERSI_VEREN { get; set; }
        public int DERS_YARI_YIL { get; set; }
    }
    public partial class alinanDersModel
    {
        public int ogrenciNo { get; set; }
        public string ogrenciAd { get; set; }
        public string ogrenciSoyad { get; set; }
        public string dersId { get; set; }
        public string sýnavNot { get; set; }
        public string sýnavTur { get; set; }
        public int dersAlmaId { get; set; }
    }
}