//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObsSistem.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class bolumModel
    {
        public string BOLUM_ID { get; set; }
        public string BOLUM_AD { get; set; }
    }
}
